### ISSUE TITLE
TypeError with gcr.io/paketo-buildpacks/nodejs:0.7.2

### ISSUE THREAD

**Issue by juergenzimmermann** [paketo-buildpacks/nodejs#448]
## What happened?
Using `gcr.io/paketo-buildpacks/nodejs:0.7.1` everything works fine, However, upgrading to `gcr.io/paketo-buildpacks/nodejs:0.7.2` I get `TypeError: Cannot read property 'integrity' of undefined`

* What were you attempting to do?
Upgrade from `0.7.1` to `0.7.2`

* What did you expect to happen?
I expected that my `project.toml` still works.

* What was the actual behavior? Please provide log output, if possible.
Log output:

```
> pack build juergenzimmermann/buch:1.0.0 --builder paketobuildpacks/builder:base

base: Pulling from paketobuildpacks/builder
Digest: sha256:6c42e7d119ef14742115fb31de8025bb981c7084e3ce4eed3444e3eef9a224cd
Status: Image is up to date for paketobuildpacks/builder:base
base-cnb: Pulling from paketobuildpacks/run
Digest: sha256:9cb1909dbe23818f37f91cf9f3cd7d0c2748b6e07c2093169b3fd15591feff27
Status: Image is up to date for paketobuildpacks/run:base-cnb
0.7.2: Pulling from paketo-buildpacks/nodejs
Digest: sha256:33b67cd3e1e4a93b870396d5ff823f6a4bcd20533fea918c7fc32981b30f039a
Status: Image is up to date for gcr.io/paketo-buildpacks/nodejs:0.7.2
===> DETECTING
6 of 9 buildpacks participating
paketo-buildpacks/ca-certificates 2.4.0
paketo-buildpacks/node-engine     0.7.1
paketo-buildpacks/npm-install     0.4.0
paketo-buildpacks/node-module-bom 0.1.1
paketo-buildpacks/npm-start       0.3.0
paketo-buildpacks/procfile        4.3.0
===> ANALYZING
Previous image with name "juergenzimmermann/buch:1.0.0" not found
Restoring metadata for "paketo-buildpacks/node-module-bom:cyclonedx-node-module" from cache
===> RESTORING
Restoring data for "paketo-buildpacks/node-module-bom:cyclonedx-node-module" from cache
===> BUILDING

Paketo CA Certificates Buildpack 2.4.0
  https://github.com/paketo-buildpacks/ca-certificates
  Launch Helper: Contributing to layer
    Creating /layers/paketo-buildpacks_ca-certificates/helper/exec.d/ca-certificates-helper
Paketo Node Engine Buildpack 0.7.1
  Resolving Node Engine version
    Candidate version sources (in priority order):
      BP_NODE_VERSION -> "16.8.0"
      package.json    -> ">=16.8.0"
      <unknown>       -> ""

    Selected Node Engine version (using BP_NODE_VERSION): 16.8.0

  Executing build process
    Installing Node Engine 16.8.0
      Completed in 6.54s

  Configuring build environment
    NODE_ENV     -> "production"
    NODE_HOME    -> "/layers/paketo-buildpacks_node-engine/node"
    NODE_VERBOSE -> "true"

  Configuring launch environment
    NODE_ENV     -> "production"
    NODE_HOME    -> "/layers/paketo-buildpacks_node-engine/node"
    NODE_VERBOSE -> "false"

    Writing profile.d/0_memory_available.sh
      Calculates available memory based on container limits at launch time.
      Made available in the MEMORY_AVAILABLE environment variable.

Paketo NPM Install Buildpack 0.4.0
  Resolving installation process
    Process inputs:
      node_modules      -> "Not found"
      npm-cache         -> "Not found"
      package-lock.json -> "Found"

    Selected NPM build process: 'npm ci'

  Executing build process
    Running 'npm ci --unsafe-perm --cache /layers/paketo-buildpacks_npm-install/npm-cache'
      Completed in 26.487s

  Configuring launch environment
    NPM_CONFIG_LOGLEVEL -> "error"

  Configuring environment shared by build and launch
    PATH -> "$PATH:/layers/paketo-buildpacks_npm-install/modules/node_modules/.bin"


Paketo Node Module Bill of Materials Generator Buildpack 0.1.1
  Resolving CycloneDX Node.js Module version
    Selected CycloneDX Node.js Module version: 3.0.6

  Executing build process
    Installing CycloneDX Node.js Module 3.0.6
      Completed in 182ms

  Configuring environment
    Appending CycloneDX Node.js Module onto PATH

  Running CycloneDX Node.js Module
    Running 'cyclonedx-bom -o bom.json'
failed to run cyclonedx-bom: exit status 1
        /layers/paketo-buildpacks_node-module-bom/cyclonedx-node-module/model/HashList.js:47
              if (lockfile.dependencies[pkg.name].integrity) {
                                                  ^

        TypeError: Cannot read property 'integrity' of undefined
            at HashList.processHashes (/layers/paketo-buildpacks_node-module-bom/cyclonedx-node-module/model/HashList.js:47:43)
            at new HashList (/layers/paketo-buildpacks_node-module-bom/cyclonedx-node-module/model/HashList.js:27:12)
            at new Component (/layers/paketo-buildpacks_node-module-bom/cyclonedx-node-module/model/Component.js:41:22)
            at Bom.createComponent (/layers/paketo-buildpacks_node-module-bom/cyclonedx-node-module/model/Bom.js:75:23)
            at /layers/paketo-buildpacks_node-module-bom/cyclonedx-node-module/model/Bom.js:86:24
            at Array.map (<anonymous>)
            at Bom.createComponent (/layers/paketo-buildpacks_node-module-bom/cyclonedx-node-module/model/Bom.js:86:10)
            at /layers/paketo-buildpacks_node-module-bom/cyclonedx-node-module/model/Bom.js:86:24
            at Array.map (<anonymous>)
            at Bom.createComponent (/layers/paketo-buildpacks_node-module-bom/cyclonedx-node-module/model/Bom.js:86:10)
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51
```

## Build Configuration
project.toml:
```
[project]
id = "com.acme.buch"
name = "Microservice buch"
version = "1.0.0"
authors = ["Juergen.Zimmermann@h-ka.de"]

[build]
include = [
  "/dist/src",
  "!/dist/src/**/*.js.map",
  "!/dist/src/**/*.d.ts",
  "!/dist/src/jest.config.*",
  "/.npmrc",
  "/.slugignore",
  "/Procfile",
  "/package*.json",
  "/project.toml",
  #"/node_modules",
]

[[build.buildpacks]]
# https://console.cloud.google.com/gcr/images/paketo-buildpacks/GLOBAL/nodejs
#uri = "gcr.io/paketo-buildpacks/nodejs:0.7.2"
uri = "gcr.io/paketo-buildpacks/nodejs:0.7.1"

[[build.env]]
name = "BP_NODE_VERSION"
value = "16.8.0"

[[build.env]]
name = "BP_LAUNCHPOINT"
value = "./dist/src/main.js"

[[build.env]]
name = "NODE_VERBOSE"
value = "true"

[[build.env]]
name = "NPM_CONFIG_LOGLEVEL"
value = "verbose"

[[build.env]]
name = "NODE_ENV"
value = "production"

[[build.env]]
name = "NPM_CONFIG_PRODUCTION"
value = "true"
```

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.
pack 0.21.0-rc1

* What buildpacks are you using? Please include versions.
See `project.toml` above.

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?
pack with `paketobuildpacks/builder:base`

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

If needed I can attach my project.

**Comment by arjun024** [comment]
Thanks for reporting the issue. This looks like the issue mentioned at https://github.com/CycloneDX/cyclonedx-node-module/issues/169 and was solved by cyclonedx-node-module v3.0.7. This has been released as part of [Node.js v0.7.3](https://github.com/paketo-buildpacks/nodejs/releases/tag/v0.7.3). Feel free to reopen the issue incase the problem persists
